// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZpHXoFhJwVb5ISBik39mxhAAaQfvqSkI',
    appId: '1:1091000878817:web:70cd40f385d39fb8ab99a0',
    messagingSenderId: '1091000878817',
    projectId: 'flutterfire-chat-d327f',
    authDomain: 'flutterfire-chat-d327f.firebaseapp.com',
    storageBucket: 'flutterfire-chat-d327f.appspot.com',
    measurementId: 'G-NZYGQGCK5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6EV04iQIRQZGUpuqwrzOcaw1IzHMyPFM',
    appId: '1:1091000878817:android:a4cc90d579781f12ab99a0',
    messagingSenderId: '1091000878817',
    projectId: 'flutterfire-chat-d327f',
    storageBucket: 'flutterfire-chat-d327f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOKBOoxRvolXeVnXsTlM9Dt4biPg3RMEc',
    appId: '1:1091000878817:ios:2f6d0c6350b24a04ab99a0',
    messagingSenderId: '1091000878817',
    projectId: 'flutterfire-chat-d327f',
    storageBucket: 'flutterfire-chat-d327f.appspot.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOKBOoxRvolXeVnXsTlM9Dt4biPg3RMEc',
    appId: '1:1091000878817:ios:2f6d0c6350b24a04ab99a0',
    messagingSenderId: '1091000878817',
    projectId: 'flutterfire-chat-d327f',
    storageBucket: 'flutterfire-chat-d327f.appspot.com',
    iosBundleId: 'com.example.flashChat',
  );
}
